### ISSUE TITLE
Fix reconc_BUIS documentation

### ISSUE THREAD

**Issue by LorenzoZambon** [IDSIA/bayesRecon#2]
The required parameters for the negative binomial distribution are mu and size (instead of mu and prob)
The correct string for specifying the negative binomial distribution is negbin (instead of nbinom)

**Comment by dazzimonti** [comment]
Updated the documentation regarding the parameters (now they are actually mu and size).

Changed the internal calls and kept the string for the negative binomial distribution as "nbinom" (consistent with R notation).
