### ISSUE TITLE
reconc_gaussian: return Full Cov

### ISSUE THREAD

**Issue by nicorbtt** [IDSIA/bayesRecon#9]
return a Full reconciled covariance matrix instead of blocks (upper / bottom)

**Comment by dazzimonti** [comment]
We won't return the full reconciled matrix because it is not positive definite. 
Proposal:
- simplify code (l384 and l386) to compute upper mean and covariance (use A)
- add explanation in documentation on why we don't return the full matrix.

**Comment by dazzimonti** [comment]
I add another proposal to be implemented to fix this issue:

- return only the reconciled parameters of the bottom variables
- in the documentation add that we return only the bottom and an explanation on how to obtain the upper parameters
- In the example of the function add a section that shows: how to obtain parameters for the upper, how to sample from the bottom, how to obtain reconciled samples by using the matrix S. 
- Note that we will need to update the tests if we return only the bottoms.
